[book]
title = "Bhikkhu Manual"
authors = ["Forest Sangha Publications"]
language = "en"
multilingual = false
src = "manuscript/markdown"

[build]
build-dir = "book"
create-missing = true

[output.html]
additional-css = ["assets/stylesheets/output-html.css"]
curly-quotes = true
