[book]
title = "Bhikkhu Manual"
authors = ["Forest Sangha Publications"]
language = "en"
multilingual = false
src = "manuscript/markdown"

[output.html]
additional-css = ["assets/stylesheets/book-custom.css"]
curly-quotes = true
