[book]
title = "Bhikkhu Manual"
authors = ["Forest Sangha Publications"]
language = "en"
multilingual = false
src = "manuscript/markdown"

[build]
build-dir = "book"
create-missing = true

[output.html]
additional-css = ["assets/stylesheets/output-html.css"]
smart-punctuation = true

[output.epub]
additional-css = ["assets/stylesheets/output-epub.css"]
use-default-css = false
cover-image = "reference-desktop-cover.jpg"
additional-resources = ["assets/fonts/NunitoSansX-Regular.ttf", "assets/fonts/NunitoSansX-Italic.ttf", "assets/fonts/NunitoSansX-Bold.ttf", "assets/fonts/OpenSansX-Regular.ttf"]
