#+TITLE: Bhikkhu Manual Feedback (2019 Apr)
#+OPTIONS: toc:t num:nil author:nil creator:nil

* Bhikkhu Manual Feedback
** feedback review 2019-04-07
   
Attached:

- manual pdf
- screenshots
- Aj Dhammasiha comments, 2 emails

Dear Ajahn Amaro and Ajahn Kevali,

Warning, long email ahead...

Quick takeaways:

- updated manual PDF attached
- English editing procedure
- possibly and extended electronic version
- new text details
- further feedback on content 

I added a number of the texts which Ajahn Kevali suggested. I attached an updated PDF with a couple of screenshots to confirm the appearance of the layout.

Please note that the page breaks and spacing are not too carefully arranged at this early stage.

The new Pali additions might have typos, please take care when reading. The source of the added texts is the Chomtong chanting book which Ajahn Kevali attached, but there is always some hand-fixing involved with these old PDFs, because their encoding is not unicode.

I also attached the extended text of Ajahn Dhammasiha's notes on quotes and translations, here I will only summarize.

Please see my questions and the feedback summaries below.

*A) planning*

I would like to ask what would the Ajahns see as a suitable procedure for reviewing English translations? Those already in the book and new ones being suggested.

For the time being I will just collect the comments and suggestions.

A number of people asked for more translations. I see two kind of requests -- some translations which are currently being used as chanting, and translations which people wish were easily accessible.

In the former case, such as the Samanera Sikkha, it seems like a good way forward to include these in the handbook.

But the latter case is real too. I have heard many times the "you can find it online" answer, but even to do that is quite complicated, and I would like to transform this answer to "here, these are the translations."

I would be glad to offer to extend the scope of this work to solve that. Not as an immediate project, but the work we are doing now prepares a good ground for it.

I could see for example an extended version of this manual in electronic formats, complete with all available translations, and a large-page format PDF which could be printed in the monasteries, maybe just a couple of copies for each dana-sala.

*B) text details*

- do you wish the Yatha anumodana with alternating lines, instead of grouped? sec.6.1, p.64
- technical check: are the annotation notes visible to you? p.17 for example, next to sec.3.4 title
- please expand on the instruction about how to organize the lines of "Moro
  carati" in sec.4.14, p.39, I didn't understand Aj Kevali's earlier notes
- Mahamangala: please review how the line breaks would make sense, sec.4.32 on p.53

*C) added sections in the attached PDF*

- Mahamangala cakka vala: sec.4.32, p.53
- Closing parittas chant: sec.4.37, p.58
- Sambuddhe: sec.4.5, p.27
- Yatha in Pali and English: sec.6.1, p.64
- Anumodana Chant for Offering Senasana: sec.6.12, p.71
- the 7-part Abhidhamma-Chanting: sec.7.3 onward, p.76
- Samanera-Sikkha in Pali and English: sec.9.4, p.113
- Parting Chant for laypeople taking leave after Wan Phra: sec.16.12.1 and sec.16.12.2, from p.183
- update the Sanghadana apalokana kamma: sec.16.4, p.168

Vinaya:

- The Kathina Pali Sanghakamma: sec.15.4.3, p.164

*D) further suggestions on content*

Ajahn Kevali also suggested the following:

- a standard formula that monks from Sri Lanka utter as a dialogue while they greet each other.
- standard ceremony of disrobing
- The Kathina-Dana apalokana for the first and second monk in English

Ajahn Dhammasiha suggested new quotes:

- 'Ye dhammā hetuppabhavā...' /Mv.1.23.5/ (Ven. Assaji's response to Ven. Sariputta)
- 'Atthi, bhikkhave, ajātaṃ...' /Ud. 8.3/ (The Unconditioned)
- 'Atthi, bhikkhave, tad-āyatanaṃ...' /Ud. 8.1/ (There is that sphere where there is neither earth...)
- Anupubbasikkhā, Gradual Training

Ajahn Dhammasiha suggesting edits to English translations:

- "Suvaco" as "easy to teach", "amiable to training", "capable to accept instruction", "willing to be admonished"
- The Three Kinds of Suffering
- The 3 Universal Characteristics of Experience

Ajahn Appamado suggested:

- translations in English for the Patimokkha chants
- Anumodana translations

Ajahn Kusalo suggested:

- not interested in the Sri Lankan versions and chants

That's all for now...

Anjali,
Gambhiro

** Tasks                                                           :noexport:
** Notes                                                           :noexport:
*** Contact list                                                   :noexport:
 
[2019-03-28] Sent out cover letter to start circulating the PDF.

[[mu4e:msgid:87imw3wije.fsf@gmail.com][preparing a new edition of the Bhikkhu Manual]]

Contact list:

#+begin_src
Amaro Bhikkhu <amaro@amaravati.org>,

Ajahn Kevali <aj.kevali@forestsangha.net>,
Wat Pah Nanachat <watpahnanachat19@gmail.com>,
Ajahn Nyanadhammo <watratanawan@gmail.com>,

Dhammagiri <dhgi@posteo.org>,

Temple Forest Monastery <jayanto@jetagrove.us>,
Jayanto Bhikkhu <b.jayanto@gmail.com>,

Pacific Hermitage <hermitage@abhayagiri.org>,
Sudanto Bhikkhu <sudanto@abhayagiri.org>,

Lokuttara <lokuttara.secretary@gmail.com>,
Ajahn Gavesako <gavesako@gmail.com>,
kalyano bhikkhu <tankalyano@gmail.com>,

Ahimsako Bhikkhu <ahimsako@gmail.com>

Sumedharama <mosteirotheravada@gmail.com>,
Tisarana Buddhist Monastery <viradhammo@tisarana.ca>,
Santacittarama <santacittarama@gmail.com>,
Bodhinyanarama <ajahn@kusalo.net>,
Vimutti Buddhist Monastery <vimutti.atba@gmail.com>,
Dhammapala <info@dhammapala.ch>,
Aruna Ratanagiri Buddhist Monastery <sangha@ratanagiri.org.uk>,
Ajahn Munindo <ajahnmunindo@ratanagiri.org.uk>,

Cittaviveka Buddhist Monastery <office@cittaviveka.org>,
Ajahn Karuniko <b.karuniko@gmail.com>,
Ahimsako Bhikkhu <ahimsako@gmail.com>,

Hartridge Buddhist Monastery <hartridge.monastery@gmail.com>,
Abhayagiri Monastery <vihara@abhayagiri.org>,
Bodhivana <buddhabodhivana@gmail.com>,
Wat Buddha Dhamma <wbdoffice@gmail.com>,
#+end_src

*** Responses
**** Aj Kevali (notes)

[[mu4e:msgid:SG2PR01MB28867A9755C0D92F91B1164BBC570@SG2PR01MB2886.apcprd01.prod.exchangelabs.com][RE: preparing a new edition of the Bhikkhu Manual]]

- [X] Sambuddhe
- [X] Mahamangala cakka vala
- [X] the 7-part Abhidhamma-Chanting
- [X] Samanera-Sikkha in Pali and English
- [X] Yatha in Pali and English
- [X] Closing parittas chant
- [X] Anumodana Chant for Offering Senasana
- [X] Parting Chant for laypeople taking leave after Wan Phra
- [X] update the Sanghadana apalokana kamma

Source: Chomtong Chanting book

Vinaya:

- [X] The Kathina Pali Sanghakamma for transferring the robe to the recipient

- [ ] there seems to be a standard formula that monks from Sri Lanka utter as a
  dialogue while they greet each other. This would make sense to include, as
  there is already much reference to the Sri Lankan tradition in there.

- [ ] I wonder if the standard ceremony of disrobing should be in there. It
  happens more often than one thinks.

- [ ] The Kathina-Dana apalokana for the first and second monk in English in a
  standardized version could be included.

**** Aj Dhammasiha (notes)

[[mu4e:msgid:3747e26c-a4f9-0c42-8e5d-c83155694c79@dhammagiri.org.au][Re: preparing a new edition of the Bhikkhu Manual]]

[[mu4e:msgid:44ZgGj3wGbz6tmJ@submission01.posteo.de][Suggestions for New Bhikkhu Manual Aj Dhammasiha]]

New address: =Dhammagiri <dhgi@posteo.org>=

Suggesting new quotes:

- 'Ye dhammā hetuppabhavā...' /Mv.1.23.5/ (Ven. Assaji's response to Ven. Sariputta)
- 'Atthi, bhikkhave, ajātaṃ...' /Ud. 8.3/ (The Unconditioned)
- 'Atthi, bhikkhave, tad-āyatanaṃ...' /Ud. 8.1/ (There is that sphere where there is neither earth...)
- Anupubbasikkhā, Gradual Training

Suggesting edits to English translations:

- "Suvaco" as "easy to teach", "amiable to training", "capable to accept instruction", "willing to be admonished"
- The Three Kinds of Suffering
- The 3 Universal Characteristics of Experience

**** Aj Appamado (notes)

[[mu4e:msgid:CA+wdS1m7M+YOJ=paPEs1rbosVy1gLp_DUyEd0Or2H8TuGPCFYA@mail.gmail.com][Re: preparing a new edition of the Bhikkhu Manual]]

- [ ] translations in English for the Patimokkha chants
- [ ] Anumodana translations

**** Aj Kusalo (notes)

[[mu4e:msgid:5C9D0BF1.7050103@kusalo.net][ajK book]]

- not interested the Sri Lankan versions and chants
- more English translations

**** Aj Karuniko (ack)

'looks a quite adequate and comprehensive'

**** Aj Jayanto (ack)

'Great idea'

**** Aj Viradhammo (ack)

'Sadhu to you and Ajahn Amaro. I especially liked Appendix B with those Useful Notes.'

**** Aj Sucitto (ack)
